insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (111, 'Dataminers', '2345 street-42', 'Greenville', 'SC', 28262, '9876543210', 'dminers@abc.com', 'Jon', 'The company works with data warehousing, data minign and database designing.', 'www.dataminer.com', 'Software', 'Database'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (112, 'SqlStars', '4567 mickey street', 'Columbia', 'SC', 28462, '9876543762', 'sqlstars@abc.com', 'Haarthi', 'The company works with different kinds of sql platforms.', 'www.sqlstars.com', 'Database Systems', 'Database'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (113, 'GoNiner', '876 street tryon', 'Charlotte', 'SC', 28272, '9876543435', 'niner@abc.com', 'Rohit', 'The company manufactures and produces sports goods sold all over US.', 'www.goniner.com', 'Sports', 'Sports'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (114, 'InSphere', '323 Berry apartments', 'Albany', 'NY', 28266, '9876543678', 'insphere@abc.com', 'Yanghai','The company is a software development firm working with various technologies.', 'www.insphere.com', 'Software', 'Software'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (115, 'FoodStruck', '768 Mallard creek', 'North Jersey', 'NJ', 28269, '9876544510', 'Foodstruck@abc.com', 'Saideep','The company food chain of various restraunts over US.', 'www.foodstruck.com', 'Food', 'Food'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (116, 'EventOrg', '6780 North street', 'Buffalo', 'NY', 45263, '9876543267', 'eventorg@abc.com', 'Deepthi', 'The company organizes events for universities, coapnies and firms.', 'www.eventorg.com', 'Marketing', 'Event organizing'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (117, 'GameArena', '56 church street', 'South Jersey', 'NJ', 43265, '9876543217', 'gamearena@abc.com', 'Gatha', 'The company is game development, marketing and advertising.', 'www.gamearena.com', 'Software', 'Gaming'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (118, 'MomAndYou', '2134 pinnacle street', 'Austin', 'Texas', 26112, '9876543216', 'momandyou@abc.com', 'Akshay','The company owns various stores and places where clothes are produced and sold over US.', 'www.momandyou.com', 'Manufacturing Clothes', 'Cloth'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (119, '24Sales', '342 homer street', 'Dallas', 'Texas', 25462, '9876546320', '24sales@abc.com', 'Naveen', 'The company is an ecommerce site', 'www.24sales.com', 'Ecommerce', 'Ecommerce'); 

insert into business (`business_id`, `business_name`, `address`, `city`, `state`, `zipcode`, `contact_phone`, `contact_email`, `contact_name`, `business_profile`, `website`, `business_type`, `industry`) values (120, 'SuperRolls', '673 prank street', 'Watertown', 'NY', 28762, '9876548754', 'superrolls@abc.com', 'John', 'The company produces chocolate rolls which are sold at different stores in US.', 'www.superrolls.com', 'Production', 'Groceries'); 