insert into login(login_id, pw, email) values (1,'usa1111','admin1@uncc.edu');
insert into login(login_id, pw, email) values (2,'jj2222','kimisgreat@kim.com');
insert into login(login_id, pw, email) values (3,'in3333', 'bill@microsoft.com');
insert into login(login_id, pw, email) values (4,'lol4444','jimmy@mymail.com');
insert into login(login_id, pw, email) values (5,'haha5555', 'john@genericemail.com');
insert into login(login_id, pw, email) values (6,'cat6666', 'jerrybush@gmail.com');
insert into login(login_id, pw, email) values (7,'dog7777', 'obama@whitehouse.com');
insert into login(login_id, pw, email) values (8,'fun8888', 'bigguy@funny.comm');
insert into login(login_id, pw, email) values (9,'happy9999', 'catty@gmail.com');
insert into login(login_id, pw, email) values (10,'cc1010', 'bill@dbmanager.com');
insert into login(login_id, pw, email) values (11,'gg1111', 'john@dbmanager.com');
